version: '3'
services:
  elasticsearch: # 服务名称
    image: elasticsearch:7.1.1      # 使用的镜像
    container_name: elasticsearch_1   # 容器名称
#    restart: on-failure:3               # 失败自动重启策略
    environment:
      - node.name=node-0                                           # 节点名称，集群模式下每个节点名称唯一
      - network.publish_host=172.20.0.30                          # 用于集群内各机器间通信,其他机器访问本机器的es服务
      - network.host=0.0.0.0                                        # 设置绑定的ip地址，可以是ipv4或ipv6的，默认为0.0.0.0，
      - discovery.seed_hosts=172.20.0.10,172.20.0.20,172.20.0.30            # es7.x 之后新增的配置，写入候选主节点的设备地址，在开启服务后可以被选为主节点
      - cluster.initial_master_nodes=172.20.0.10,172.20.0.20,172.20.0.30     # es7.x 之后新增的配置，初始化一个新的集群时需要此配置来选举master
      - cluster.name=es-cluster                                     # 集群名称，相同名称为一个集群
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"    # 设置内存
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /d/docker/container-data/elk/elasticsearch1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  # 将容器中es的配置文件映射到本地，设置跨域， 否则head插件无法连接该节点
      - es1_data:/usr/share/elasticsearch/data  # 存放数据的文件， 注意：这里的esdata为 顶级volumes下的一项。
    ports:
      - 9201:9200    # http端口
      - 9301:9300    # es节点直接交互的端口，非http
    networks:
      elk:
        ipv4_address: 172.20.0.10
volumes:
  es1_data:
    driver: local    # 会生成一个对应的目录和文件，如何查看，下面有说明。

networks:
  default:
    external:
      name: elk
  elk:
    external: true

