version: '1'
services:
  teamcity-agent-local: # 服务名称
    image: "jetbrains/teamcity-server:2021.2-linux"    # 使用的镜像
    container_name: teamcity-server                     # 容器名称
    user: root
#    environment: # 环境变量
#    privileged: true
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
      - /opt/teamcity/logs:/opt/teamcity/logs   # 映射es容器中的配置文件到宿主机
    hostname: teamcityserver                                       # 服务hostname
    ulimits: # 是否限制内存
      memlock:
        soft: -1
        hard: -1
    #    restart: always                                                 # 重启策略
    ports:
      - "8111:8111"                                                   # http端口

volumes: # 顶级volumes
  teamcity_data:
    driver: local                                                   # 会生成一个对应的目录和文件，如何查看，下面有说明。
